config/routes.rb
Rails.application.routes.draw do
  resources :suppliers do
    resources :facturas, :controller => 'hefesto/facturas'
    resources :recibos,  :controller => 'hefesto/recibos'
    resources :notacreditos, :controller => 'hefesto/notacreditos'
    resources :facturanotacreditos,  :controller => 'hefesto/facturanotacreditos'
    resources :facturarecibos, :controller => 'hefesto/facturarecibos'

    member do
      get 'list_accounts', :action => :list_accounts
      get 'cuentacorriente', :action => :cuentacorriente 
    end
  end
end

app/models/cliente.rb
# == Schema Information
# Schema version: 20110512124317
#
# Table name: clientes
#
#  id              :integer         not null, primary key
#  codigo          :string(255)
#  razonsocial     :string(255)
#  cuit            :string(255)
#  telefono        :string(255)
#  direccion       :string(255)
#  contacto        :string(255)
#  created_at      :datetime
#  updated_at      :datetime
#  condicioniva_id :integer
#  empresa_id      :integer
#

class Cliente < ActiveRecord::Base
  has_many :facturas
  has_many :recibos
  has_many :notacreditos
  has_many :comprobantes do 
    def saldo
      fc = where("Type = 'Factura'").sum(:importe)
      nc = where("Type = 'Notacredito'").sum(:importe)
      rc = where("Type = 'Recibo'").sum(:importe)
      fc - nc - rc
    end
  end
   
  belongs_to :condicioniva
  belongs_to :account
  
  #belongs_to :empresa

  validates :cuit, :presence => true, :length => { :maximum => 11 }
  validates :razonsocial, :presence => true
  validates :codigo, :presence => true
  validates_uniqueness_of :codigo, :scope => [:empresa_id]
  validates_uniqueness_of :cuit, :scope => [:empresa_id]

  validates_numericality_of :cuit, :only_integer => true, :message => "solo numeros"
  # validates_inclusion_of :cuit, :in => 20000000000..38000000000, :message => "solo puede ingresar numeros entre 20 y 38."

  attr_accessible :razonsocial, :condicioniva_id, :codigo, :cuit, :telefono, :direccion, :contacto, :empresa_id, :account_id

  scope :sin_telefono, where("clientes.telefono = '' ")
  scope :no_actualizados, where("updated_at IS NULL" )
  scope :orden_alfabetico, order("clientes.razonsocial")  
  scope :by_company, lambda {|company| where(:empresa_id => company.id) }
  
  delegate :saldo , :to => :comprobantes
  
  # control para 
  before_destroy :control_sin_comprobantes
  
  # funcionalidad: accesible_by(current_ability)) 
  # 1) rails g cancan:ability
  
  def control_sin_comprobantes

   if [comprobantes].any? {|cpbte| cpbte.any? }
     self.errors[:base] = "error que queres hacer?"
     return false
   end   
  end
  
end

app/views/clientes/_form.html.erb
<%= semantic_form_for(@cliente) do |f| %>
<%= f.semantic_errors %>

<%= f.inputs do %>
  <%= f.input :codigo %>
  <%= f.input :razonsocial %>
  <%= f.input :cuit, :as => :numeric , :input_html => { :size => 11, :style => "text-align:left;" }%>
  <%= f.input :condicioniva, :label => true, :as => :select, :collection => Condicioniva.all.map{|c| [c.detalle, c.id]}, :include_blank => false %>
  <%= f.input :telefono %>
  <%= f.input :direccion %>
  <%= f.input :contacto %>
  <%= f.input :account, :label => true, :as => :select, :collection => 
current_company.accounts.leaves.map{|a|[a.self_and_ancestors.map(&:name).join(' &raquo; ').html_safe, a.id]} , :include_blank => true %>
<% end %> 

<%= f.buttons %>
<% end %>

app/views/clientes/_sidebar.html.erb
<% content_for(:sidebar) do %>
<div class='block'>
  <ul class='navigation'>    
    <li><%= link_to("Nueva Factura", new_cliente_factura_path(@cliente))%></li>
    <li><%= link_to("Nuevo Recibo", new_recibo_path)%></li>
    <li><%= link_to("Nueva Nota de credito", new_notacredito_path)%></li>
	
    <li><%= link_to("Facturas vs Recibos", facturarecibos_path)%></li>
    <li><%= link_to("Facturas vs Notas de credito", facturanotacreditos_path)%></li>
	<li><%= link_to("Cuenta corriente", cuentacorriente_cliente_path(@cliente) )%></li>
  </ul>
</div>
<%end%>

app/views/clientes/cuentacorriente.html.erb
<h1>Listado de cuenta corriente del cliente <%= @cliente.razonsocial %></h1>
<table>
 <tr>
    <th>T.C.</th>	
    <th>Numero</th>
    <th>Fecha</th>
    <th>Importe</th>
    <th>Fecha Vto</th>
    <th>Fecha Registro</th>
  </tr>
<% @cuentacorriente.each do |cpbte| %>
  <tr>
    <td><%= cpbte.type %></td>	
    <td align="right"><%= cpbte.numero %></td>
    <td><%= cpbte.fecha %></td>
    <td align="right"><%= cpbte.total %></td>
    <td><%= cpbte.fechavto %></td>
	<td><%= cpbte.created_at %></td>
  </tr>
<% end %>
<tr>
  <td>Saldo</td>	
  <td></td>
  <td></td>
  <td align="right"><%= @cliente.saldo %></td>
  <td></td>
</tr>
</table>

<%= link_to 'Volver', cliente_path(@cliente) %>

app/views/clientes/show.html.erb
<% content_for(:breadcrumbs) do %>
<%= breadcrumbs do |b|
	b.item "Principal", root_path
    b.item "Clientes", clientes_path
    b.item @cliente.razonsocial, root_path, :active => true
end %>
<%end%>

<%= render 'sidebar' %>

<%= semantic_attributes_for @cliente do |attr| %>
  <%= attr.attributes do %>
	<%= attr.attribute :razonsocial , :label => "Razón social"%>
	<%= attr.attribute :cuit %>
   	<%= attr.attribute :telefono %>
   	<%= attr.attribute :direccion %>
  	<%= attr.attribute :contacto , :label => "Contacto", :display_empty => true %>
   	<%= attr.attribute :condicioniva_id, :display_empty => true, :value => @cliente.condicioniva.try('detalle') %>
   	<%= attr.attribute :account_id, :display_empty => true, :value => @cliente.account.try('name') %>
  <% end %>
<% end %>
<hr>
<p>
  <b>Facturas</b>
</p>
<table>
 <tr>
    <th>Numero</th>
    <th>Fecha</th>
    <th>Importe</th>
    <th>Fecha Vto</th>
  </tr>
<% @cliente.facturas.each do |cpbte| %>
  <tr>
    <td><%= cpbte.numero %></td>
    <td><%= cpbte.fecha %></td>
    <td><%= cpbte.importe %></td>
    <td><%= cpbte.fechavto %></td>
  </tr>

	<% cpbte.facturarecibos.each do |cpbteafectado| %>
  		<tr>
    		<td>recibo -------></td>
    		<td><%= cpbteafectado.fecha %></td>
    		<td><%= cpbteafectado.importe %></td>
	  		<td><%= cpbteafectado.recibo.numero %></td>
	  		<td><%= cpbteafectado.recibo.importe %></td>
  		</tr>
	<% end %>
	
	<% cpbte.facturanotacreditos.each do |cpbteafectado| %>
		<tr>
  		<td>nota credito --></td>
  		<td><%= cpbteafectado.fecha %></td>
  		<td><%= cpbteafectado.importe %></td>
  		<td><%= cpbteafectado.factura.numero %></td>
  		<td><%= cpbteafectado.factura.totalfactura %></td>
		</tr>
	<% end %>	
<% end %>
</table>

<hr>
<p>
  <b>Recibos</b>
</p>
<table>
 <tr>
    <th>Numero - </th>
    <th>Fecha - </th>
    <th>Importe</th>
  </tr>

<% #raise @cliente.recibos.inspect %>
<% @cliente.recibos.each do |cpbte| %>

  <tr>
    <td><%= cpbte.numero %></td>
    <td><%= cpbte.fecha %></td>
    <td><%= cpbte.importe %></td>
  </tr>
	<% cpbte.facturarecibos.each do |cpbteafectado| %>
		<tr>
  		<td>factura -------></td>
  		<td><%= cpbteafectado.fecha %></td>
  		<td><%= cpbteafectado.importe %></td>
  		<td><%= cpbteafectado.factura.numero %></td>
  		<td><%= cpbteafectado.factura.totalfactura %></td>
		</tr>
	<% end %>	
<% end %>
</table>

<hr>
<p>
  <b>Nota de credito</b>
</p>
<table>
 <tr>
    <th>Numero</th>
    <th>Fecha</th>
    <th>Importe</th>
  </tr>
<% @cliente.notacreditos.each do |cpbte| %>
  <tr>
    <td><%= cpbte.numero %></td>
    <td><%= cpbte.fecha %></td>
    <td><%= cpbte.importe %></td>
  </tr>
	<% cpbte.facturanotacreditos.each do |cpbteafectado| %>
		<tr>
		<td>factura -------></td>
		<td><%= cpbteafectado.fecha %></td>
		<td><%= cpbteafectado.importe %></td>
  		<td><%= cpbteafectado.factura.numero %></td>
  		<td><%= cpbteafectado.factura.totalfactura %></td>
		</tr>
	<% end %>
<% end %>
</table>

<%= link_to 'Editar', edit_cliente_path(@cliente) %> |
<%= link_to 'Volver', clientes_path %>