config/routes.rb
Rails.application.routes.draw do
  resources :suppliers do
    resources :facturas, :controller => 'hefesto/facturas'
    resources :recibos,  :controller => 'hefesto/recibos'
    resources :notacreditos, :controller => 'hefesto/notacreditos'
    resources :facturanotacreditos,  :controller => 'hefesto/facturanotacreditos'
    resources :facturarecibos, :controller => 'hefesto/facturarecibos'

    member do
      get 'list_accounts', :action => :list_accounts
      get 'cuentacorriente', :action => :cuentacorriente 
    end
  end
end

app/models/hefesto/comprobante.rb
# == Schema Information
# Schema version: 20110516183603
#
# Table name: comprobantes
#
#  id         :integer         not null, primary key
#  cliente_id :integer
#  type       :string(255)
#  fecha      :date
#  importe    :decimal(, )
#  numero     :integer
#  fechavto   :date
#  printed_at :date
#  created_at :datetime
#  updated_at :datetime
#
module Hefesto
  class Comprobante < ActiveRecord::Base
    set_table_name :compra_comprobantes
    
    belongs_to :supplier  
    has_many :detalles, :class_name => "Hefesto::Detalle", :as => :detallable do
      def calculo_total_items
        map(&:totalitem).sum
      end
    end
  
    before_validation :calculo_total_comprobante
  
    accepts_nested_attributes_for :detalles, :allow_destroy => true, :reject_if => :all_blank  
  
    validates :fecha, :presence => true
    validates :numero, :presence => true, :length => { :maximum => 10 }, :uniqueness => true, :numericality => true
    validates_numericality_of :importe, :greater_than => 0

    #TODO importe debe ser la suma de los totales de los items
    #validates :importe, :presence => true, :numericality => true
  
    def count_items
      detalles.count
    end
    
    def total
      detalles.calculo_total_items
    end  
  
    protected
    def calculo_total_comprobante
      #self.importe =  self.total
      self.importe = 100
    end
  end
end

app/models/hefesto/detalle.rb
# == Schema Information
# Schema version: 20110516183603
#
# Table name: detalles
#
#  id              :integer         not null, primary key
#  detallable_id   :integer
#  detallable_type :string(255)
#  descripcion     :string(255)
#  cantidad        :decimal(, )
#  preciounitario  :decimal(, )
#  created_at      :datetime
#  updated_at      :datetime
#  tasaiva         :decimal(, )
#
module Hefesto
  class Detalle < ActiveRecord::Base
    set_table_name :compra_detalles
       
    belongs_to :detallable,:class_name => "Hefesto::Detalle", :polymorphic => true
  
    attr_accessible :cantidad, :descripcion, :preciounitario, :tasaiva
    attr_accessor :totalitem

    #validates :cantidad, :presence => true , :numericality => true, :numericality => { :greater_than => 0 }
    #validates :preciounitario, :presence => true, :numericality => true, :numericality => { :greater_than => 0 }
    #validates :descripcion, :presence => true
    #validates :tasaiva, :presence => true, :numericality => true
  
    def totalivaitem
      self.tasaiva = 0 if self.tasaiva.nil?
      self.preciounitario = 0 if self.preciounitario.nil?
      self.cantidad = 0 if self.cantidad.nil?
    
      self.preciounitario * self.cantidad * (self.tasaiva/100)
    end  

    def totalitem
      self.tasaiva = 0 if self.tasaiva.nil?
      self.preciounitario = 0 if self.preciounitario.nil?
      self.cantidad = 0 if self.cantidad.nil?
    
      self.preciounitario * self.cantidad * (1 + (self.tasaiva/100))
    end  
  end
end

app/models/hefesto/facturanotacredito.rb
# == Schema Information
# Schema version: 20110427202648
#
# Table name: facturanotacreditos
#
#  id             :integer         not null, primary key
#  factura_id     :integer
#  fecha          :date
#  importe        :decimal(, )
#  notacredito_id :integer
#  created_at     :datetime
#  updated_at     :datetime
#
module Hefesto
  class Facturanotacredito < ActiveRecord::Base
    belongs_to :factura
    belongs_to :notacredito
    has_one :supplier, :through => :factura
  end
end

app/controllers/hefesto/facturanotacreditos_controller.rb
module Hefesto
  class FacturanotacreditosController < AuthorizedController
    # GET /facturanotacreditos
    # GET /facturanotacreditos.xml
    def index
      @facturanotacreditos = Facturanotacredito.all

      respond_to do |format|
        format.html # index.html.erb
        format.xml  { render :xml => @facturanotacreditos }
      end
    end

    # GET /facturanotacreditos/1
    # GET /facturanotacreditos/1.xml
    def show
      @facturanotacredito = Facturanotacredito.find(params[:id])

      respond_to do |format|
        format.html # show.html.erb
        format.xml  { render :xml => @facturanotacredito }
      end
    end

    # GET /facturanotacreditos/new
    # GET /facturanotacreditos/new.xml
    def new
      @facturanotacredito = Facturanotacredito.new

      respond_to do |format|
        format.html # new.html.erb
        format.xml  { render :xml => @facturanotacredito }
      end
    end

    # GET /facturanotacreditos/1/edit
    def edit
      @facturanotacredito = Facturanotacredito.find(params[:id])
    end

    # POST /facturanotacreditos
    # POST /facturanotacreditos.xml
    def create
      @facturanotacredito = Facturanotacredito.new(params[:facturanotacredito])

      respond_to do |format|
        if @facturanotacredito.save
          format.html { redirect_to(@facturanotacredito, :notice => 'Facturanotacredito was successfully created.') }
          format.xml  { render :xml => @facturanotacredito, :status => :created, :location => @facturanotacredito }
        else
          format.html { render :action => "new" }
          format.xml  { render :xml => @facturanotacredito.errors, :status => :unprocessable_entity }
        end
      end
    end

    # PUT /facturanotacreditos/1
    # PUT /facturanotacreditos/1.xml
    def update
      @facturanotacredito = Facturanotacredito.find(params[:id])

      respond_to do |format|
        if @facturanotacredito.update_attributes(params[:facturanotacredito])
          format.html { redirect_to(@facturanotacredito, :notice => 'Facturanotacredito was successfully updated.') }
          format.xml  { head :ok }
        else
          format.html { render :action => "edit" }
          format.xml  { render :xml => @facturanotacredito.errors, :status => :unprocessable_entity }
        end
      end
    end

    # DELETE /facturanotacreditos/1
    # DELETE /facturanotacreditos/1.xml
    def destroy
      @facturanotacredito = Facturanotacredito.find(params[:id])
      @facturanotacredito.destroy

      respond_to do |format|
        format.html { redirect_to(facturanotacreditos_url) }
        format.xml  { head :ok }
      end
    end
  end
end

app/controllers/hefesto/facturarecibos_controller.rb
module Hefesto
  class FacturarecibosController < AuthorizedController
    # GET /facturarecibos
    # GET /facturarecibos.xml
    def index
      @facturarecibos = Facturarecibo.all

      respond_to do |format|
        format.html # index.html.erb
        format.xml  { render :xml => @facturarecibos }
      end
    end

    # GET /facturarecibos/1
    # GET /facturarecibos/1.xml
    def show
      @facturarecibo = Facturarecibo.find(params[:id])

      respond_to do |format|
        format.html # show.html.erb
        format.xml  { render :xml => @facturarecibo }
      end
    end

    # GET /facturarecibos/new
    # GET /facturarecibos/new.xml
    def new
      @facturarecibo = Facturarecibo.new

      respond_to do |format|
        format.html # new.html.erb
        format.xml  { render :xml => @facturarecibo }
      end
    end

    # GET /facturarecibos/1/edit
    def edit
      @facturarecibo = Facturarecibo.find(params[:id])
    end

    # POST /facturarecibos
    # POST /facturarecibos.xml
    def create
      @facturarecibo = Facturarecibo.new(params[:facturarecibo])

      respond_to do |format|
        if @facturarecibo.save
          format.html { redirect_to(@facturarecibo, :notice => 'Facturarecibo was successfully created.') }
          format.xml  { render :xml => @facturarecibo, :status => :created, :location => @facturarecibo }
        else
          format.html { render :action => "new" }
          format.xml  { render :xml => @facturarecibo.errors, :status => :unprocessable_entity }
        end
      end
    end

    # PUT /facturarecibos/1
    # PUT /facturarecibos/1.xml
    def update
      @facturarecibo = Facturarecibo.find(params[:id])

      respond_to do |format|
        if @facturarecibo.update_attributes(params[:facturarecibo])
          format.html { redirect_to(@facturarecibo, :notice => 'Facturarecibo was successfully updated.') }
          format.xml  { head :ok }
        else
          format.html { render :action => "edit" }
          format.xml  { render :xml => @facturarecibo.errors, :status => :unprocessable_entity }
        end
      end
    end

    # DELETE /facturarecibos/1
    # DELETE /facturarecibos/1.xml
    def destroy
      @facturarecibo = Facturarecibo.find(params[:id])
      @facturarecibo.destroy

      respond_to do |format|
        format.html { redirect_to(facturarecibos_url) }
        format.xml  { head :ok }
      end
    end
  end
end

app/controllers/hefesto/facturas_controller.rb
module Hefesto 
  class FacturasController < AuthorizedController
    before_filter :find_supplier
    before_filter :find_factura, :except => [:index, :new, :create]
    # GET /facturas
    # GET /facturas.xml
  
    def index
      #@search = @supplier.search(params[:search])
      #@facturas = @search.page(params[ :page ]).per(10)
      
      @facturas = @supplier.facturas
      
      respond_to do |format|
        format.html # index.html.erb
        format.xml  { render :xml => @facturas }
      end
    end

    # GET /facturas/1
    # GET /facturas/1.xml
    def show
      respond_to do |format|
        format.html # show.html.erb
        format.xml  { render :xml => @factura }
        format.pdf do

          #unless @factura.isprinted?
             @entry = @factura.to_entry
             unless @entry.save
               flash[:error] = @entry.errors.full_messages.join("\n")
               redirect_to [@factura.supplier,:facturas]
               return
             end
          #end

          dump_tmp_filename = Rails.root.join('tmp',@factura.cache_key)
          Dir.mkdir(dump_tmp_filename.dirname) unless File.directory?(dump_tmp_filename.dirname)
          @factura.save_pdf_to(dump_tmp_filename)
          send_file(dump_tmp_filename, :type => :pdf, :disposition => 'attachment', :filename => "#{@supplier.razonsocial}-factura-#{@factura.numero}.pdf")
          File.delete(dump_tmp_filename)
        end
      end
    end

    # GET /facturas/new
    # GET /facturas/new.xml
    def new
      @factura = @supplier.facturas.build

      respond_to do |format|
        format.html # new.html.erb
        format.xml  { render :xml => @factura }
      end
    end

    # GET /facturas/1/edit
    def edit
    end

    # POST /facturas
    # POST /facturas.xml
    def create
      @factura = @supplier.facturas.build(params[:hefesto_factura])
      
      respond_to do |format|
        if @factura.save
          format.html { redirect_to([@supplier, @factura], :notice => 'Factura was successfully created.') }
          format.xml  { render :xml => @factura, :status => :created, :location => [@supplier, @factura] }
        else
          format.html { render :action => "new" }
          format.xml  { render :xml => @factura.errors, :status => :unprocessable_entity }
        end
      end
    end

    # PUT /facturas/1
    # PUT /facturas/1.xml
    def update
      respond_to do |format|
        if @factura.update_attributes(params[:factura])
          format.html { redirect_to([@supplier, @factura], :notice => 'Factura was successfully updated.') }
          format.xml  { head :ok }
        else
          format.html { render :action => "edit" }
          format.xml  { render :xml => @factura.errors, :status => :unprocessable_entity }
        end
      end
    end

    # DELETE /facturas/1
    # DELETE /facturas/1.xml
    def destroy
      @factura.destroy unless @factura.isprinted?

      respond_to do |format|
        format.html { redirect_to(supplier_facturas_url(@supplier)) }
        format.xml  { head :ok }
      end
    end
  
  protected
  
  def find_supplier
    @supplier = Supplier.find(params[:supplier_id])
  end

  def find_factura
    @factura = @supplier.facturas.find(params[:id])
  end
end

end

app/controllers/hefesto/notacreditos_controller.rb
module Hefesto
  class NotacreditosController < AuthorizedController
    # GET /notacreditos
    # GET /notacreditos.xml
    before_filter :authenticate_user!
  
    def index
      @notacreditos = Notacredito.all

      respond_to do |format|
        format.html # index.html.erb
        format.xml  { render :xml => @notacreditos }
      end
    end

    # GET /notacreditos/1
    # GET /notacreditos/1.xml
    def show
      @notacredito = Notacredito.find(params[:id])

      respond_to do |format|
        format.html # show.html.erb
        format.xml  { render :xml => @notacredito }
      end
    end

    # GET /notacreditos/new
    # GET /notacreditos/new.xml
    def new
      @notacredito = Notacredito.new

      respond_to do |format|
        format.html # new.html.erb
        format.xml  { render :xml => @notacredito }
      end
    end

    # GET /notacreditos/1/edit
    def edit
      @notacredito = Notacredito.find(params[:id])
    end

    # POST /notacreditos
    # POST /notacreditos.xml
    def create
      @notacredito = Notacredito.new(params[:notacredito])

      respond_to do |format|
        if @notacredito.save
          format.html { redirect_to(@notacredito, :notice => 'Notacredito was successfully created.') }
          format.xml  { render :xml => @notacredito, :status => :created, :location => @notacredito }
        else
          format.html { render :action => "new" }
          format.xml  { render :xml => @notacredito.errors, :status => :unprocessable_entity }
        end
      end
    end

    # PUT /notacreditos/1
    # PUT /notacreditos/1.xml
    def update
      @notacredito = Notacredito.find(params[:id])

      respond_to do |format|
        if @notacredito.update_attributes(params[:notacredito])
          format.html { redirect_to(@notacredito, :notice => 'Notacredito was successfully updated.') }
          format.xml  { head :ok }
        else
          format.html { render :action => "edit" }
          format.xml  { render :xml => @notacredito.errors, :status => :unprocessable_entity }
        end
      end
    end

    # DELETE /notacreditos/1
    # DELETE /notacreditos/1.xml
    def destroy
      @notacredito = Notacredito.find(params[:id])
      @notacredito.destroy

      respond_to do |format|
        format.html { redirect_to(notacreditos_url) }
        format.xml  { head :ok }
      end
    end
  end
end

app/controllers/hefesto/recibos_controller.rb
module Hefesto
  class RecibosController < AuthorizedController
    # GET /recibos
    # GET /recibos.xml
  
    def index
      @search = Recibo.search(params[:search])
      @recibos = @search.page(params[ :page ]).per(10)

      respond_to do |format|
        format.html # index.html.erb
        format.xml  { render :xml => @recibos }
      end
    end

    # GET /recibos/1
    # GET /recibos/1.xml
    def show
      @recibo = Recibo.find(params[:id])

      respond_to do |format|
        format.html # show.html.erb
        format.xml  { render :xml => @recibo }
      end
    end

    # GET /recibos/new
    # GET /recibos/new.xml
    def new
      @recibo = Recibo.new

      respond_to do |format|
        format.html # new.html.erb
        format.xml  { render :xml => @recibo }
      end
    end

    # GET /recibos/1/edit
    def edit
      @recibo = Recibo.find(params[:id])
    end

    # POST /recibos
    # POST /recibos.xml
    def create
      @recibo = Recibo.new(params[:recibo])

      respond_to do |format|
        if @recibo.save
          format.html { redirect_to(@recibo, :notice => 'Recibo was successfully created.') }
          format.xml  { render :xml => @recibo, :status => :created, :location => @recibo }
        else
          format.html { render :action => "new" }
          format.xml  { render :xml => @recibo.errors, :status => :unprocessable_entity }
        end
      end
    end

    # PUT /recibos/1
    # PUT /recibos/1.xml
    def update
      @recibo = Recibo.find(params[:id])

      respond_to do |format|
        if @recibo.update_attributes(params[:recibo])
          format.html { redirect_to(@recibo, :notice => 'Recibo was successfully updated.') }
          format.xml  { head :ok }
        else
          format.html { render :action => "edit" }
          format.xml  { render :xml => @recibo.errors, :status => :unprocessable_entity }
        end
      end
    end

    # DELETE /recibos/1
    # DELETE /recibos/1.xml
    def destroy
      @recibo = Recibo.find(params[:id])
      @recibo.destroy

      respond_to do |format|
        format.html { redirect_to(recibos_url) }
        format.xml  { head :ok }
      end
    end
  end
end

app/helpers/hefesto/facturadetalles_helper.rb
module Hefesto::FacturadetallesHelper
end

app/helpers/hefesto/facturanotacreditos_helper.rb
module Hefesto::FacturanotacreditosHelper
end

app/helpers/hefesto/facturarecibos_helper.rb
module Hefesto::FacturarecibosHelper
end

app/helpers/hefesto/facturas_helper.rb
module Hefesto::FacturasHelper
end

app/helpers/hefesto/notacreditos_helper.rb
module Hefesto::NotacreditosHelper
end

app/helpers/hefesto/recibos_helper.rb
module Hefesto::RecibosHelper
end

app/views/hefesto/facturas/_detalle_fields.html.erb
<div class="nested-fields">
	<%= f.inputs do %>
	<table>
		<tr>
			<td><%= f.input :descripcion , :label => false, :as => :text, :input_html => {:style => "text-align:left; width:250px;height:30px"} %></td>
	        <td><%= f.input :cantidad, :label => false, :as => :numeric, :input_html => { :class => :para_calcula, :onblur => 'calcula_total(this);', :size => 10, :style => "text-align:right;"} %></td>

			<td><%= f.input :preciounitario, :label => false, :as => :numeric,:input_html => {:onblur => 'calcula_total(this);', :class => :para_calcula, :size => 10, :style => "text-align:right;"} %></td>

			<td><%= f.input :tasaiva, :label => false, :as => :numeric,:input_html => {:onblur => 'calcula_total(this);', :class => :para_calcula, :size => 10, :style => "text-align:right;"} %></td>

			<td align='right'><%= content_tag(:span, f.object.totalitem, :class => 'calcula_total') %></td>					

			<td><%= link_to_remove_association "borrar", f %></td>
		</tr>
	</table>
	<% end %>		
</div>

app/views/hefesto/facturas/_filtros.html.erb
<% content_for(:filtros) do %>
<div id="filters" class="accordion">
  <h3><a href="#">Filtros</a></h3>
  <div class="filters-content">
	<%= semantic_form_for @search do |f| %>
	   <%= f.inputs do %>
	   <%= f.input :numero_equals, :label => "Numero de factura" %>
	   <%= f.input :fecha_greater_than_or_equal_to, :label => "Desde fecha" %>	
	   <%= f.input :fecha_less_than_or_equal_to, :label => "Hasta fecha" %>	
	   <% end %>
	   <%= f.buttons do %>
	      <%= f.commit_button :search %>
	   <% end %>
	<% end %>
  </div>
</div>
<%end%>

app/views/hefesto/facturas/_form.html.erb
<% content_for(:head) do %>
  <%= javascript_tag do %>
    function calcula_total(input){
      var total = parseFloat($($(input).closest('tr').find('input.para_calcula')[0]).val()) * 	parseFloat($($(input).closest('tr').find('input.para_calcula')[1]).val()) * 
(1 + (parseFloat($($(input).closest('tr').find('.tasaiva')).val())/100));

      $($(input).closest('tr').find('.calcula_total')[0]).html(total.toFixed(2));
      var total_total=0.0;
      $('.calcula_total').each(function(i,data){
	    total_total+=parseFloat($(data).html());
      });
      $('.total_total').html(total_total.toFixed(2));
    }
  <% end %>
<% end %>

<% content_for(:head) do %>
  <%= javascript_tag do %>
    function pasa_tasa(select){
		$.getJSON('/products/'+$(select).val(), function(data) {
		  $(select).closest('tr').find('.tasaiva').val(data.porcentaje);
		  $(select).closest('tr').find('.preciounitario').val(data.price);
		  $(select).closest('tr').find('.description').val(data.description);
		  
		  $(select).closest('tr').find('.labeltasaiva').html(data.porcentaje.toFixed(2));
		
		  calcula_total($(select).closest('tr').find('.tasaiva'));
		  $(select).closest('tr').find('.cantidad').focus();
		});
    }
  <% end %>
<% end %>

<%= semantic_form_for [@supplier, @factura] do |f| %>
 <%= f.semantic_errors %>
 <%= f.semantic_errors(:importe) %>

	<%= f.inputs do %>
	  <%= f.input :fecha , :as => :date %>
	  <%= t('activerecord.attributes.supplier.razonsocial') + ' : ' + @supplier.razonsocial %>
	  <%= f.input :numero , :as => :numeric, :input_html => { :size => 10, :style => "text-align:right;" } %>
	  <%= f.input :fechavto , :as => :date %>
	<table>
		<tr>
			<th>Descripcion</th>
			<th>Cantidad</th>
			<th>Precio unitario</th>
			<th>tasa IVA</th>
			<th>Total item</th>
			<th> </th>		
		</tr>
	</table>

	<div class="links">
		<%= link_to_add_association icon('add', :small, :style => 'vertical-align:middle;')+'Agrega detalle', f, :detalles,'data-association-insertion-position' => :after , :class => 'global_button button'%>
	</div>

	<div class='detalles'>
		<%= f.semantic_fields_for :detalles do |fd|%>    
	    	<%= render 'detalle_fields', :f => fd %> 
		<% end %>
	</div>
	<% end %>
<%= render('shared/common_form_buttons') %>
<% end %>

app/views/hefesto/facturas/edit.html.erb
<h1>Editando factura</h1>

<%= render 'form' %>

<%= link_to 'Ver', @factura %> |
<%= link_to 'Volver', facturas_path %>

app/views/hefesto/facturas/index.html.erb
<% content_for(:breadcrumbs) do %>
<%= breadcrumbs do |b|
  b.item t('scaffold.actions.main'), root_path
  b.item t('activerecord.models.supplier'), suppliers_path
end %>
<%end%>

<table>
  <tr>
    <th>Proveedor</th>
    <th>Fecha</th>
    <th align="center">Importe Total</th>
    <th align="center">Numero</th>
    <th>Fecha vencimiento</th>
	<th>Items Totales</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
<% @facturas.each do |factura| %>
  <tr>
    <td><%= factura.supplier.try(:razonsocial) %></td>
    <td><%= factura.fecha %></td>
    <td align="right"><%= factura.total %></td>
    <td align="right"><%= factura.numero %></td>
    <td><%= factura.fechavto %></td>
    <td><%= factura.count_items %></td>
    <td><%= link_to icon('application_go', :small, :title => 'ver'), supplier_hefesto_factura_path(factura.supplier,factura) %></td>
<% if factura.isprinted? %>
	<td></td>
	<td></td>
<% else %>
    <td><%= link_to icon('application_edit', :small, :title => 'editar'), edit_factura_path(factura) %></td>
<% end %>
    <td><%= link_to icon('printer', :small, :title => 'Imprimir'), print_supplier_hefesto_factura_path(factura.supplier, factura ) %></td>
  </tr>
<% end %>
</table>
<br/>
<br/>

app/views/hefesto/facturas/new.html.erb
<h1>Nueva factura</h1>

<% content_for(:controls) do %>
<%= controls do |c|
         c.item "Volver", supplier_path(@factura.supplier), :icon => "application_go"
end %>
<%end%>

<%= render 'form' %>

app/views/hefesto/facturas/show.html.erb
<%= semantic_attributes_for @factura do |attr| %>
  <%= attr.attributes "Cabecera" do %>

  	<%= attr.attribute :fecha %>
  	<%= attr.attribute :numero , :label => "Numero de factura"%>
  	<%= attr.attribute :total, :label => "Total de factura" %>
  	<%= attr.attribute :fechavto %>

	<%= attr.attributes :for => :supplier do |supplier| %>
		<%= supplier.attribute :razonsocial , :label => "Razón social"%>
	 	<%= supplier.attribute :cuit %>
   	  	<%= supplier.attribute :telefono %>
   	  	<%= supplier.attribute :direccion %>
	<% end.html_safe %>

  	<%= attr.attribute :count_items, :label => "Cantidad de items en la factura" %>
  <% end %>
<% end %>

<table>
  <tr>
	 <th>Descripcion</th>
	 <th align="center">Cantidad</th>
	 <th align="center">Precio unitario</th>
	 <th align="center">IVA</th>
	 <th align="center">Precio total</th>
	 <th></th>
	 <th></th>
	 <th></th>	
  </tr>
<% @factura.detalles.each do |item| %>
  <tr>
    <td align="left" ><%= item.descripcion %></td>
    <td align="right"><%= item.cantidad %></td>
    <td align="right"><%= number_to_currency(item.preciounitario) %></td>
    <td align="right"><%= number_to_percentage(item.tasaiva, :precision => 2) %></td>
    <td align="right"><%= number_to_currency(item.totalitem) %></td>
  </tr>
<% end %>
<tr>
  <td align="left" ><b>Total :</b></td>
  <td align="right"></td>
  <td align="right"></td>
  <td align="right"></td>
  <td align="right"><%= number_to_currency(@factura.total) %></td>
</tr>
</table>
</br>
<%= link_to 'Editar', edit_supplier_hefesto_factura_path(@factura.supplier,@factura) %> |
<%= link_to 'Volver', suppliers_path %>