config/routes.rb
Rails.application.routes.draw do
  resources :suppliers do
    resources :facturas, :controller => 'hefesto/facturas'
    resources :recibos,  :controller => 'hefesto/recibos'
    resources :notacreditos, :controller => 'hefesto/notacreditos'
    resources :facturanotacreditos,  :controller => 'hefesto/facturanotacreditos'
    resources :facturarecibos, :controller => 'hefesto/facturarecibos'

    member do
      get 'list_accounts', :action => :list_accounts
      get 'cuentacorriente', :action => :cuentacorriente 
    end
  end
end

app/models/supplier.rb
# == Schema Information
# Table name: suppliers
#
#  id              :integer         not null, primary key
#  codigo          :string(255)
#  razonsocial     :string(255)
#  cuit            :string(255)
#  telefono        :string(255)
#  direccion       :string(255)
#  contacto        :string(255)
#  created_at      :datetime
#  updated_at      :datetime
#  condicioniva_id :integer
#  company_id      :integer
#

class Supplier < ActiveRecord::Base
  has_many :facturas, :class_name => '::Hefesto::Factura'
  has_many :recibos, :class_name => '::Hefesto::Recibo'
  has_many :notacreditos, :class_name => '::Hefesto::Notacredito'
  has_many :comprobantes, :foreign_key => "cliente_id" do 
    def saldo
      fc = where("Type = 'Hefesto::Factura'").sum(:importe)
      nc = where("Type = 'Hefesto::Notacredito'").sum(:importe)
      rc = where("Type = 'Hefesto::Recibo'").sum(:importe)
      fc - nc - rc
    end
  end
   
  belongs_to :condicioniva
  belongs_to :account

  validates :cuit, :presence => true, :length => { :maximum => 11 }
  validates :razonsocial, :presence => true
  validates :codigo, :presence => true
  validates_uniqueness_of :codigo, :scope => [:company_id]
  validates_uniqueness_of :cuit, :scope => [:company_id]

  validates_numericality_of :cuit, :only_integer => true, :message => "solo numeros"

  attr_accessible :razonsocial, :condicioniva_id, :codigo, :cuit, :telefono, :direccion, :contacto, :company_id, :account_id

  scope :sin_telefono, where("suppliers.telefono = '' ")
  scope :no_actualizados, where("updated_at IS NULL" )
  scope :orden_alfabetico, order("suppliers.razonsocial")  
  scope :by_company, lambda {|company| where(:company_id => company.id) }
  
  delegate :saldo , :to => :comprobantes
  
  before_destroy :control_sin_comprobantes

  def save_ctacte_pdf_to(filename,entity)
    require 'prawn'
    pdf = Prawn::Document.new(:left_margin => 35, :top_margin => 35,:page_size   => "LETTER",
                              :page_layout => :portrait)
    offset = 0

    pdf.repeat(:all, :dynamic => true) do
      pdf.draw_text ("Cuenta corriente de " + entity.first.supplier.razonsocial + " impreso el " + Date.today.strftime("%d/%m/%Y")) , :at => [5,745],:style => :bold, :size => 10
      pdf.draw_text "Hoja Nro.: " + pdf.page_number.to_s.rjust(4,"0"), :at => [300, 745],:style => :bold, :size => 8
    end
    data = [["Fecha","Tipo Cp","Numero","Importe","Fecha Vto","impreso"],[] ]
    saldo = 0
    entity.each do |r|
       data << [r.fecha.blank? ? '' : r.fecha.strftime("%d/%m/%Y"),
                r.type,
                r.numero,
                r.total_comprobante,
                r.fechavto.blank? ? '' : r.fechavto.strftime("%d/%m/%Y"),
                r.printed_at.blank? ? '' : r.printed_at.strftime("%d/%m/%Y")]
        saldo += r.total_comprobante       
    end
    data << ["" ,"Totales","",saldo.to_s,"",""  ]

    pdf.table(data, :column_widths => [65, 100, 60, 65, 65, 65],
             :cell_style => { :font => "Times-Roman",
                              :size => 10,:padding => [2,3,4,2],
                              :align =>  :left,
                              :valign => :center },
             :header => true ,
             :row_colors => ["F0F0F0", "FFFFCC"]
              ) do
      column(2...3).align = :right
      row(0).column(0..6).align = :center
    end
    pdf.render_file(filename)
  end
    
  def control_sin_comprobantes
   if [comprobantes].any? {|cpbte| cpbte.any? }
     self.errors[:base] = "error que queres hacer?"
     return false
   end   
  end
end

app/controllers/suppliers_controller.rb
class SuppliersController < AuthorizedController
  # GET /suppliers
  # GET /suplierss.xml
  before_filter :filter_supplier, :only => [:show,:edit,:update,:destroy,:cuentacorriente]
  
  def index
    @search = Supplier.by_company(current_company).search(params[:search])
    @suppliers = @search.order("razonsocial").page(params[ :page ]).per(10)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @suppliers }
      format.pdf do
         dump_tmp_filename = Rails.root.join('tmp',@suppliers.first.cache_key)
         Dir.mkdir(dump_tmp_filename.dirname) unless File.directory?(dump_tmp_filename.dirname)
         save_list_pdf_to(dump_tmp_filename,@suppliers) 
         send_file(dump_tmp_filename, :type => :pdf, :disposition => 'attachment', :filename => "proveedores.pdf")
         File.delete(dump_tmp_filename)           
      end
    end
  end

  def show
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @supplier }
      format.pdf do
        dump_tmp_filename = Rails.root.join('tmp',@supplier.cache_key)
        Dir.mkdir(dump_tmp_filename.dirname) unless File.directory?(dump_tmp_filename.dirname)
        save_pdf_to(dump_tmp_filename,@supplier)
        send_file(dump_tmp_filename, :type => :pdf, :disposition => 'attachment', :filename => "#{@supplier.razonsocial}.pdf")
        File.delete(dump_tmp_filename)
      end
    end
  end

  def new
    @supplier = current_company.suppliers.build

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @supplier }
    end
  end

  def edit
  end

  def create
    @supplier = Supplier.new(params[:supplier].update(:company_id => current_company.id))

    respond_to do |format|
      if @supplier.save
        format.html { redirect_to(@supplier, :notice => 'Proveedor was successfully created.') }
        format.xml  { render :xml => @supplier, :status => :created, :location => @supplier }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @supplier.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @supplier.update_attributes(params[:supplier])
        format.html { redirect_to(@supplier, :notice => 'Proveedor was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @supplier.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @supplier.destroy

    respond_to do |format|
      format.html { redirect_to(supplier_url) }
      format.xml  { head :ok }
    end
  end

  def cuentacorriente
    @cuentacorriente = @supplier.comprobantes.order("fecha")
  
    respond_to do |format|
      format.html # .html.erb
      format.xml  { render :xml => @supplier }
      format.pdf do      
        dump_tmp_filename = Rails.root.join('tmp',@supplier.cache_key)
        Dir.mkdir(dump_tmp_filename.dirname) unless File.directory?(dump_tmp_filename.dirname)
        @supplier.save_ctacte_pdf_to(dump_tmp_filename,@cuentacorriente)
        send_file(dump_tmp_filename, :type => :pdf, :disposition => 'attachment', :filename => "#{@supplier.razonsocial}-ctacte.pdf")
        File.delete(dump_tmp_filename)
      end
    end
  end

def list_accounts
  #begin
    @accounts = Account.all()

    respond_to do |format|
      format.html { redirect_to( clientes_url ) }
      format.xml  { head :ok }
    end
  #rescue ActiveResource::ResourceNotFound, ActiveResource::Redirection, ActiveResource::ResourceInvalid
  #  redirect_to("404.html")
  #ensure
    # redirect_to("404.html")
    # paso siempre por aca
  #end
end

protected 
# filtro general protejido
  def filter_supplier
    @supplier = Supplier.by_company(current_company).find( params[:id] )
  end
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/views/suppliers/_filtros.html.erb
<% content_for(:filtros) do %>
<div id="filters" class="accordion">
  <h3><a href="#">Filtros</a></h3>
  <div class="filters-content">
	<%= semantic_form_for @search do |f| %>
	   <%= f.inputs do %>
	   <%= f.input :razonsocial_contains, :label => "Razon social" %>
	   <%= f.input :cuit_contains, :label => "CUIT" %>	
	   <% end %>
	   <%= f.buttons do %>
	      <%= f.commit_button :search %>
	   <% end %>
	<% end %>
  </div>
</div>
<%end%>

app/views/suppliers/_form.html.erb
<%= semantic_form_for(@supplier) do |f| %>
<%= f.semantic_errors %>

<%= f.inputs(:class => :column_left ) do %>
  <%= f.input :codigo %>
  <%= f.input :razonsocial %>
  <%= f.input :fantasyname %>
  <%= f.input :cuit, :as => :numeric , :input_html => { :size => 11, :style => "text-align:left;" }%>
  <%= f.input :condicioniva_id, :as => :select, :collection => current_company.condicionivas.all.map{|c| [c.detalle, c.id]}, :include_blank => false %>
  <%= f.input :observation %>
<% end %>

<%= f.inputs(:class => :column_right ) do %>
  <%= f.input :telefono %>
  <%= f.input :direccion %>
  <%= f.input :locality %>		
  <%= f.input :province_id, :as => :select, :collection => Province.all.map{|c| [c.name, c.id]}, :include_blank => false %>
  <%= f.input :postalcode %>	
  <%= f.input :email, :as => :string %>
  <%= f.input :contacto %>
  <%= f.input :account_id, :as => :select, :collection => 
current_company.accounts.leaves.map{|a|[a.self_and_ancestors.map(&:name).join(' &raquo; ').html_safe, a.id]} , :include_blank => true %>
<% end %>
<hr class="clear">

<%= render('shared/common_form_buttons') %>
<% end %>

app/views/suppliers/_sidebar.html.erb
<% content_for(:sidebar) do %>
<div class='block'>
  <ul class='navigation'>    
    <li><%= link_to("Nueva Factura", new_supplier_factura_path(@supplier))%></li>
    <li><%= link_to("Nuevo Recibo", new_supplier_recibo_path(@supplier))%></li>
    <li><%= link_to("Nueva Nota de credito", new_supplier_notacredito_path(@supplier))%></li>

    <li><%= link_to("Facturas vs Recibos", supplier_facturarecibos_path(@supplier))%></li>
    <li><%= link_to("Facturas vs Notas de credito", supplier_facturanotacreditos_path(@supplier))%></li>	
	  <li><%= link_to("Cuenta corriente", cuentacorriente_supplier_path(@supplier) )%></li>
  </ul>
</div>
<%end%>

app/views/suppliers/cuentacorriente.html.erb
<% content_for(:breadcrumbs) do %>
<%= breadcrumbs do |b|
	  b.item t('scaffold.actions.main'), root_path
    b.item t('activerecord.models.supplier'), suppliers_path
    b.item @supplier.razonsocial, root_path, :active => true
end %>
<%end%>

<% content_for(:controls) do %>
<%= controls do |c|
    c.item "Exportar PDF", cuentacorriente_supplier_path(@supplier, :format => 'pdf'), :icon => "report_go"
    c.item "Volver", suppliers_path, :icon => "application_go"
end %>
<%end%>

<h1>Listado de cuenta corriente del <%= @supplier.razonsocial %></h1>

<table class="table ">
 <tr>
    <th>T.C.</th>	
    <th>Numero</th>
    <th>Fecha</th>
    <th>Importe</th>
    <th>Fecha Vto</th>
    <th>Fecha Registro</th>
    <th></th>
  </tr>
<% @cuentacorriente.order('fecha').each do |cpbte| %>
  <tr>
    <td><%= cpbte.type %></td>	
    <td align="right"><%= cpbte.numero %></td>
    <td><%= cpbte.fecha %></td>
    <td align="right"><%= cpbte.total %></td>
    <td><%= cpbte.fechavto %></td>
	  <td><%= cpbte.created_at %></td>
    <td class="actions"><%= link_to icon('application_go', :small, :title => 'ver'), [@supplier, cpbte] %></td>
  </tr>
<% end %>
<tr>
  <td><b>Saldo</b></td>	
  <td></td>
  <td></td>
  <td align="right"><b><%= @supplier.saldo %></b></td>
  <td></td>
</tr>
</table>

app/views/suppliers/edit.html.erb
<h1>Editando proveedor</h1>

<% content_for(:controls) do %>
<%= controls do |c|
         c.item "Ver", supplier_path(@supplier), :icon => "application_go"
end %>
<%end%>

<% content_for(:breadcrumbs) do %>
<%= breadcrumbs do |b|
	b.item "Principal", root_path
    b.item "Proveedores", suppliers_path
    b.item @supplier.razonsocial, root_path, :active => true
end %>
<%end%>

<%= render 'form' %>

app/views/suppliers/index.html.erb
<h1>Listado de proveedores</h1>

<%= render 'filtros' %>

<% content_for(:controls) do %>
<%= controls do |c|
         c.item "Nuevo", new_supplier_path, :icon => "add"
         c.item "Exportar PDF", suppliers_path, :icon => "report_go"
end %>
<%end%>

<% content_for(:breadcrumbs) do %>
<%= breadcrumbs do |b|
	b.item "Principal", root_path
    b.item "suppliers", suppliers_path, :active => true
end %>
<%end%>

<table>
  <tr>
    <th>Codigo</th>
    <th>Razon social</th>
    <th>Cuit</th>
    <th>Condicion IVA</th>
    <th>Telefono</th>
    <th>Direccion</th>
    <th>Contacto</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @suppliers.each do |supplier| %>
  <tr>
    <td><%= supplier.codigo %></td>
    <td><%= supplier.razonsocial %></td>
    <td><%= supplier.cuit %></td>
    <td><%= supplier.condicioniva.try(:detalle) %></td>
    <td><%= supplier.telefono %></td>
    <td><%= supplier.direccion %></td>
    <td><%= supplier.contacto %></td>
    <td><%= link_to icon('application_go', :small, :title => 'ver'), supplier %></td>
    <td><%= link_to icon('application_edit', :small, :title => 'editar'), edit_supplier_path(supplier) %></td>
    <td><%= link_to icon('application_delete', :small, :title => 'borrar'), supplier, :confirm => 'Esta ud. seguro?', :method => :delete %></td>
  </tr>
<% end %>
</table>
<%= paginate @suppliers %>
<br/>
<br/>

app/views/suppliers/index.html.haml
- content_for(:breadcrumbs) do
  = breadcrumbs do |breadcrumb|
    - breadcrumb.item current_company.name.titlecase, root_path
    - breadcrumb.item Supplier.model_name.human, suppliers_path

- if can?(:create, Supplier)
  - content_for(:controls) do
    = controls do |control|
      - control.item t('scaffold.actions.new', :item => Supplier.model_name.human).titlecase, new_supplier_path, :icon => 'add'
      - control.item t('scaffold.actions.export').titlecase, suppliers_path( :format => 'pdf'), :icon => 'report_go'

#filters.accordion
  %h3
    %a{:href => "#"} Filtros
  .filters-content
    = semantic_form_for @search do |f|
      = f.inputs do
        = f.input :razonsocial_contains, :label => Supplier.human_attribute_name('razonsocial')
        = f.input :cuit_contains, :label => Supplier.human_attribute_name('cuit')
      = f.buttons do
        = f.commit_button :search

.block
  - if @suppliers.any?
    .clear
    .block{:style => 'margin:20px;'}= paginate(@suppliers)
    .clear
    %table.table
      %tr
        %th= Supplier.human_attribute_name('razonsocial')
        %th= Supplier.human_attribute_name('cuit')
        %th.last= Supplier.human_attribute_name('telefono')
        %th.last= Supplier.human_attribute_name('direccion')
        %th.last= Supplier.human_attribute_name('contacto')
        %th

      - @suppliers.each do |supplier|
        %tr
          %td= supplier.razonsocial
          %td= supplier.cuit
          %td.last= supplier.telefono
          %td.last= supplier.direccion
          %td.last= supplier.contacto
          %td.last.actions
            = link_to icon('application_get', :small, :title => t('scaffold.actions.show').titlecase), supplier
            = link_to icon('application_edit', :small, :title => t('scaffold.actions.edit').titlecase), edit_supplier_path(supplier)
            = link_to icon('application_delete', :small, :title => t('scaffold.actions.destroy').titlecase), supplier, :confirm => t('scaffold.actions.destroy_confirm').titlecase, :method => :delete
    .clear
    .block{:style => 'margin:20px;'}= paginate(@suppliers)
    %br
    .clear
.clear

app/views/suppliers/new.html.erb
<h1>Nuevo proveedor</h1>

<%= render 'form' %>

<%= link_to 'Volver', suppliers_path %>

app/views/suppliers/show.html.erb
<% content_for(:breadcrumbs) do %>
<%= breadcrumbs do |b|
	b.item "Principal", root_path
    b.item "Suppliers", suppliers_path
    b.item @supplier.razonsocial, root_path, :active => true
end %>
<%end%>

<% content_for(:controls) do %>
<%= controls do |c|
    c.item "Exportar PDF", supplier_path( :format => 'pdf'), :icon => "report_go"
    c.item "Editar", edit_supplier_path(@supplier), :icon => "application_form_edit"
    c.item "Volver", suppliers_path, :icon => "application_go"
end %>
<%end%>

<%= render 'sidebar' %>

<%= semantic_attributes_for @supplier do |attr| %>
  <%= attr.attributes do %>
	<%= attr.attribute :razonsocial , :label => "Razón social"%>
	<%= attr.attribute :cuit %>
   	<%= attr.attribute :telefono %>
   	<%= attr.attribute :direccion %>
  	<%= attr.attribute :contacto , :label => "Contacto", :display_empty => true %>
   	<%= attr.attribute :condicioniva_id, :display_empty => true, :value => @supplier.condicioniva.try('detalle') %>
   	<%= attr.attribute :account_id, :display_empty => true, :value => @supplier.account.try('name') %>
  <% end %>
<% end %>
<hr>
<p>
  <b>Facturas</b>
</p>
<table>
 <tr>
    <th>Numero</th>
    <th>Fecha</th>
    <th>Importe</th>
    <th>Fecha Vto</th>
  </tr>
<% @supplier.facturas.each do |cpbte| %>
  <tr>
    <td><%= cpbte.numero %></td>
    <td><%= cpbte.fecha %></td>
    <td><%= cpbte.importe %></td>
    <td><%= cpbte.fechavto %></td>
  </tr>	
<% end %>
</table>

<hr>
<p>
  <b>Recibos</b>
</p>
<table>
 <tr>
    <th>Numero - </th>
    <th>Fecha - </th>
    <th>Importe</th>
  </tr>

<% #raise @supplier.recibos.inspect %>
<% @supplier.recibos.each do |cpbte| %>

  <tr>
    <td><%= cpbte.numero %></td>
    <td><%= cpbte.fecha %></td>
    <td><%= cpbte.importe %></td>
  </tr>
<% end %>
</table>

<hr>
<p>
  <b>Nota de credito</b>
</p>
<table>
 <tr>
    <th>Numero</th>
    <th>Fecha</th>
    <th>Importe</th>
  </tr>
<% @supplier.notacreditos.each do |cpbte| %>
  <tr>
    <td><%= cpbte.numero %></td>
    <td><%= cpbte.fecha %></td>
    <td><%= cpbte.importe %></td>
  </tr>
<% end %>
</table>